Set string pointer s to point to a string literal containing two null characters
This is needed because it could lead to overruning the *u16 array.

Full SAST report:
Error: OVERRUN (CWE-119):
libarchive/archive_write_set_format_iso9660.c:2240: alias: Assigning: "s" = """". "s" now points to byte 0 of """" (which consists of 1 bytes).
libarchive/archive_write_set_format_iso9660.c:2259: alias: Assigning: "u16" = "s". "u16" now points to byte 0 of """" (which consists of 1 bytes).
libarchive/archive_write_set_format_iso9660.c:2262: overrun-local: Overrunning array of 1 bytes at byte offset 1 by dereferencing pointer "u16++".
2260|
2261|                   size = 0;
2262|->                 while (*u16++)
2263|                           size += 2;
2264|                   if (size > l)