Initialize struct tm with zero instead of empty
This fixes an issue building on Windows:

archive_read_support_format_rar.c(1871): error C2059: Syntax error: "}"

So my Visual Studio 2022 doesn't like {} as initializer for the structure.